#!/bin/bash
## Crafted (c) 2022 by Encora - We are stronger together
## Prepared : Roberto Nogueira
## File     : site
## Project  : rails-site-manager
## Reference: bash
## Depends  : fping, screen.
## Purpose  : Help to manage ordinary things.

# set -x

export SITE_VERSION=v1.0.00
export SITE_VERSION_DATE=2022.06.05
export SITE_UPDATE_MESSAGE=""
export SITES="clockwork_web"

# git and ruby domains
domain.git(){
  local domain=$(echo $(git config user.email) | awk -F\@ '{print $2}' | awk -F\. '{print $1}')
  echo $domain
}
domain.git.methods(){ echo "methods|help|encora.init|encora|gmail.init|gmail"; }
domain.git.help(){ printf "\e[1;37m%s \e[0m \e[1;36m%s\e[0m\n" "domain.git" "[$(domain.git.methods)]"; }
domain.git.encora.init(){ encora_name=$1; encora_email=$2; }
domain.git.encora(){
  git config --global user.name "$encora_name"
  git config --global user.email "$encora_email"
}
domain.git.gmail.init(){ gmail_name=$1; gmail_email=$2; }
domain.git.gmail(){
  git config --global user.name "$gmail_name"
  git config --global user.email "$gmail_email"
}
domain.ruby.init(){ ruby_print=$1; }
domain.ruby.methods(){ echo "init|methods|help|print"; }
domain.ruby.help(){ printf "\e[1;37m%s \e[0m \e[1;36m%s\e[0m\n" "domain.ruby" "[$(domain.ruby.methods)]"; }
domain.ruby.print(){
  local ruby_version
  local rails_version
  if [ "$ruby_print" = "true" ]; then 
    if hash rvm 2>/dev/null; then
      if test $(rvm current) == 'system'; then
        ruby_version="ruby-$(ruby --version | awk '{print $2}' | cut -d 'p' -f 1)"
        if hash rails 2>/dev/null; then
          rails_version="rails-$(rails --version | awk '{print $2}')"
          printf "\e[1;34m%s \e[0m%s\n" "  system    " "$ruby_version@$rails_version"
        else
          printf "\e[1;34m%s \e[0m%s\n" "  system    " "$ruby_version"
        fi
      else
        ruby_version=$(rvm current)
        if hash rails 2>/dev/null; then
          rails_version="rails-$(rails --version | awk '{print $2}')"
        else
          rails_version=""
        fi
        printf "\e[1;34m%s \e[0m%s\n" "  rvm domain" "$ruby_version@$rails_version"
      fi
    else
      ruby_version="ruby-$(ruby --version | awk '{print $2}' | cut -d 'p' -f 1)"
      if hash rails 2>/dev/null; then
        rails_version="rails-$(rails --version | awk '{print $2}')"
        printf "\e[0;34m%s \e[0m%s\n" "  system    " "$ruby_version@$rails_version"
      else
        printf "\e[0;34m%s \e[0m%s\n" "  system    " "$ruby_version"
      fi
    fi
  fi 
}

#projects
projects(){
  tl | sed 's/^/  /' 
}
projects.init(){ projects_print=$1; }
projects.methods(){ echo "init|methods|help|ls|print"; }
projects.help(){ printf "\e[1;37m%s \e[0m \e[1;36m%s\e[0m\n" "projects" "[$(projects.methods)]"; }
projects.ls(){ tdpl; }
projects.print(){
  if [ "$projects_print" = "true" ]; then
    echo -e "projects:"
    projects
  fi
}

# databases
dbs.init(){
  unset MYSQL_DATABASE_DEV
  unset MYSQL_DATABASE_TST
  MYSQL_DATABASE_DEV=$(test -f config/database.yml && dbs.parse_yml config/database.yml | grep development_database | awk -F'"' '{print $2}')
  MYSQL_DATABASE_TST=$(test -f config/database.yml && dbs.parse_yml config/database.yml | grep test_database | awk -F'"' '{print $2}' | awk -F'<' '{print $1}')
}
dbs.methods(){ echo "init|methods|help|parse_yml|console|current|has_database|tables|has_tables|records|has_records|print_db|print"; }
dbs.help(){ printf "\e[1;37m%s \e[0m \e[1;36m%s\e[0m\n" "dbs" "[$(dbs.methods)]"; }
dbs.parse_yml(){
  local prefix=$2
  local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
  sed -ne "s|^\($s\):|\1|" \
       -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
  awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
  }'  
}
dbs.console(){
  local db=$(dbs.current)
  if [ "$(dbs.has_database $db)" == 'yes' ]; then
    mycli -uroot $db
  else   
    ansi --red-intense --no-newline $db;ansi --red " does not exist"
    ansi ""
  fi
}
dbs.current(){
  local env=$1
  if [ -z $env ]; then
    env=$RAILS_ENV
  fi
  if [ "$env" == "development" ] || [ -z $env ]; then
    if [ -z $MYSQL_DATABASE_DEV ]; then
      MYSQL_DATABASE_DEV=$(test -f config/database.yml && dbs.parse_yml config/database.yml | grep development_database | awk -F'"' '{print $2}')
    fi
    echo $MYSQL_DATABASE_DEV
  else
    if [ -z $MYSQL_DATABASE_TST ]; then
      MYSQL_DATABASE_TST=$(test -f config/database.yml && dbs.parse_yml config/database.yml | grep test_database | awk -F'"' '{print $2}' | awk -F'<' '{print $1}')
    fi
    echo $MYSQL_DATABASE_TST
  fi   
}
dbs.has_database(){
  local db=$1
  local res
  mysqlshow -uroot > /dev/null 2>&1
  if [ $? -eq 1 ]; then 
    ansi --no-newline --red-intense "==> "; ansi --white-intense "Database error"
    echo ""
  else  
    res=`mysqlshow -uroot | grep -o $db`
    if [ "$res" == $db ]; then
      echo 'yes'
    else
      echo 'no'  
    fi
  fi
}
dbs.tables(){
  local db=$1
  local s=`mysql -u root -e "SELECT count(*) AS TOTALNUMBEROFTABLES FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '$db';"`
  echo $(echo -n $s | sed 's/[^0-9]*//g' | tr -d '\n')

}
dbs.has_tables(){
  local db=$1
  local tables=$(dbs.tables $db)
  if [ ! "$tables" == '0' ] && [ ! -z $tables ]; then
    echo 'yes'
  else
    echo 'no'  
  fi
}
dbs.records(){
  local db=$1
  local s=`mysql -u root -e "SELECT SUM(TABLE_ROWS) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '$1';"`
  echo $(echo -n $s | sed 's/[^0-9]*//g' | tr -d '\n')
}
dbs.has_records(){
  local db=$1
  local records=$(dbs.records $1)
  if [ ! "$records" == '' ] && [ ! -z $records ]; then
    echo 'yes'
  else
    echo 'no'  
  fi
}
dbs.print_db(){
  local env=$1
  local db
  local dbs
  local db_lens=()
  db=$(dbs.current development)
  db_lens+=(${#db})
  db=$(dbs.current test)
  db_lens+=(${#db})
  IFS=$'\n'
  major=$(echo "${db_lens[*]}" | sort -nr | head -n1)
  unset IFS
  if [ -z $env ]; then
    env=$RAILS_ENV
  fi
  if [ "$env" == "development" ]; then
    db=$(dbs.current development)
  else  
    db=$(dbs.current test)
  fi
  db=$(printf "%-${major}s" "${db}")
  if [ "$(dbs.has_database $db)" == 'yes' ]; then
    if [ $env == "development" ]; then
      ansi --no-newline "  "; ansi --no-newline --green $db' '; ansi --white --no-newline $(dbs.tables $db)' '; ansi --white $(dbs.records $db)
    else
      ansi --no-newline "  "; ansi --no-newline --green $db' '; ansi --white --no-newline $(dbs.tables $db)' '; ansi --white $(dbs.records $db)
    fi  
  else  
    ansi --no-newline "  "; ansi --red $db
  fi
}
dbs.print(){
  if test $(site.is_site) = 'yes'; then
    echo -e "dbs:"
    dbs.print_db development
    dbs.print_db test 
  fi  
}

# services
services.methods(){ echo "methods|help|start|stop"; }
services.help(){ printf "\e[1;37m%s \e[0m \e[1;36m%s\e[0m\n" "services" "[$(services.methods)]"; }
services.start(){
  local site=$([[ ! -z "$s1" ]] && echo $1 ]] || echo $(site.name))
  case $site in
    clockwork_web)
      foreman start -f Procfile.dev
      ;;
    *)
      printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${1}"
     ;;   
  esac    
}
services.stop(){
  local site=$([[ ! -z "$s1" ]] && echo $1 ]] || echo $(site.name))
  case $site in
    clockwork_web)
      pkill "foreman: master"
      ;;
    *)
      printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${1}"
     ;;   
  esac    
}
services.print_up(){
  local service=$1
  local major=$2
  local pid=$3
  case $service in
    redis)
      if [ ! -z $pid ]; then
        service=$(printf "%-${major}s" "redis")
        ansi --no-newline "  ${service} ";
        ansi --no-newline --underline --green "localhost:6379";ansi " $pid"
      fi
      ;;
    mysql)
      if [ ! -z $pid ]; then
        service=$(printf "%-${major}s" "mysql")
        ansi --no-newline "  ${service} ";
        ansi --no-newline --underline --green "localhost:3306";ansi " $pid"
      fi  
      ;;
    assets)
      if [ ! -z $pid ]; then
        service=$(printf "%-${major}s" "assets")
        ansi --no-newline "  ${service} ";
        ansi --no-newline --underline --green "yarn.js watch ";ansi " $pid"
      fi 
      ;;
    worker)
      if [ ! -z $pid ]; then
        service=$(printf "%-${major}s" "worker")
        ansi --no-newline "  ${service} ";
        ansi --no-newline --underline --green "http://localhost:3000/sidekiq";ansi " $pid"
      fi 
      ;;
    web)
      if [ ! -z $pid ]; then
        service=$(printf "%-${major}s" "web")
        ansi --no-newline "  ${service} ";
        ansi --no-newline --underline --green-intense "http://localhost:3000";ansi " $pid"
      fi  
      ;;
  esac
}
services.print_ups(){
  local pid_redis=$(netstat -anv | grep LISTEN | grep "[.]6379" | awk '{print $9}' | uniq | head -1)
  local pid_mysql=$(netstat -anv | grep LISTEN | grep "[.]3306" | awk '{print $9}' | uniq)
  local pid_assets=$(ps | grep 'yarn.js watch' | grep -v grep | awk '{print $2}')
  local pid_worker=$(ps | grep sidekiq | grep -v grep | awk '{print $2}')
  local pid_web=$(test -f tmp/pids/server.pid && cat "tmp/pids/server.pid")
  local services=(redis mysql assets worker web)
  local service_name_lens=()
  local major
  for s in ${services[@]}
  do
    pid=pid_${s}
    if ! test -z ${!pid}; then
      service_name_lens+=(${#s})
    fi
  done
  IFS=$'\n'
  major=$(echo "${service_name_lens[*]}" | sort -nr | head -n1)
  unset IFS
  for s in ${services[@]}
  do
    pid=pid_${s}
    if ! test -z ${!pid}; then
      services.print_up $s $major ${!pid}
    fi
  done
}
services.print_down(){
  local service=$1
  local last=$2
  local pid=$3
  if [ -z $pid ]; then
    if [ "$last" == "true" ]; then
      ansi --red "$service";
    else
      ansi --no-newline --red "$service";
    fi 
  fi
}
services.print_downs(){
  local pid_redis=$(netstat -anv | grep LISTEN | grep "[.]6379" | awk '{print $9}' | uniq | head -1)
  local pid_mysql=$(netstat -anv | grep LISTEN | grep "[.]3306" | awk '{print $9}' | uniq)
  local pid_assets=$(ps | grep 'yarn.js watch' | grep -v grep | awk '{print $2}')
  local pid_worker=$(test -f tmp/pids/sidekiq.pid && cat "tmp/pids/sidekiq.pid")
  local pid_web=$(test -f tmp/pids/server.pid && cat "tmp/pids/server.pid")
  local services_not_running
  local services=(redis mysql assets worker web)
  for s in ${services[@]}
  do
    pid=pid_${s}
    if test -z ${!pid}; then
      services_not_running+=($s)
    fi
  done
  if ! test -z $services_not_running; then
    ansi --no-newline "  "
    for s in ${services_not_running[@]}
    do
      if [ "$s" == "${services_not_running[${#services_not_running[@]}-1]}" ]; then
        services.print_down $s true ${!pid}
      else  
        services.print_down $s false ${!pid}
        ansi --no-newline ", "
      fi
    done
  fi  
}
services.print(){
  if test $(site.is_site) = 'yes'; then
    ansi "services:"
    services.print_ups
    services.print_downs
  fi
}

# site
site(){
  local site_methods="+($(site.methods))"
  local param_methods="+($(! test -z "$1" && $1.methods))"
  case $1 in
    --version|-v|v|version)
      site.version
      ;;
    --help|-h|h|help)
      printf "\e[1;37m%s \e[0m\n" "Crafted (c) 2021~22 by Encora - We are stronger together"
      site.version
      printf "\e[1;37m%s \e[0m%s\n" "site" "[$(site.help)]" 
      printf "\n"  
      printf "\e[1;37m%s \e[0m%s\n" "site" "[$(domain.git.help)]"
      printf "\e[1;37m%s \e[0m%s\n" "site" "[$(domain.ruby.help)]"
      printf "\n"  
      printf "\e[1;37m%s \e[0m%s\n" "site" "[$(projects.help)]"
      printf "::\n"  
      printf "\e[1;37m%s \e[0m%s\n" "site" "[$(dbs.help)]"
      printf "\e[1;37m%s \e[0m%s\n" "site" "[$(services.help)]"
      printf "::\n"  
      printf "\e[0;32m%s \e[4m%s\e[0m\e[0m\n" "homepage" "https://github.com/enogrob/rails-site-manager"
      printf "\n"
      ;;
    $site_methods)
      if [ -z "$2" ]; then
        $1 
      else  
        case $2 in
          $param_methods)
            $1.$2 ${@:3}
            ;;
          *)
            printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${2}"
            ;;  
        esac
      fi  
      ;;
    *)
      if [ -z "$1" ]; then
        site.print
      else   
        printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${1}"
      fi  
      ;;
  esac
}
site.methods(){ echo "dbs|methods|name|help|encora|domain|print|projects|services"; }
site.name(){
  if test $(site.is_site) = 'no'; then
    echo "$USER@$(hostname)" 
  else
    echo "$(basename $PWD)" 
  fi  
}
site.help(){ printf "\e[1;37m%s   \e[0m \e[1;36m%s\e[0m\n" "site" "[$(site.methods)]"; }
site.is_site(){
  if test -f config/database.yml; then
    echo 'yes'
  else
    echo 'no'  
  fi
}
site.print(){
  printf "site: \e[4m\e[1;37m$(site.name)\e[0m\e[0m\n" 
  printf "\e[1;34m%s \e[0m%s\n" "  git domain" $(domain.git) 
  domain.ruby.print
  services.print
  dbs.print
  if test $(site.is_site) = 'no'; then
    projects.print
  fi  
  printf ""  
}
site.version(){
  printf "\e[0;37m%s \e[0m%s\n" "Site" "$SITE_VERSION"
  printf "\n"
}

domain.git.encora.init "Roberto Nogueira" "roberto.nogueira@encora.com"
domain.git.gmail.init "Roberto Nogueira" "enogrob@gmail.com" 
domain.ruby.init $(hash ruby 2>/dev/null && test "$?" -eq 0 && echo true)

projects.init $(test -f $HOME/Projects/project-things-today/.todayrc.sh && echo true)
